export const COUNTRIES = [
    { code: "KR", label: "대한민국 (South Korea)" },
    { code: "US", label: "미국 (United States)" },
    { code: "CN", label: "중국 (China)" },
    { code: "JP", label: "일본 (Japan)" },
    { code: "PH", label: "필리핀 (Philippines)" },
    { code: "CA", label: "캐나다 (Canada)" },
    { code: "AU", label: "호주 (Australia)" },
    { code: "GH", label: "가나 (Ghana)" },
    { code: "GA", label: "가봉 (Gabon)" },
    { code: "GY", label: "가이아나 (Guyana)" },
    { code: "GM", label: "감비아 (Gambia)" },
    { code: "GT", label: "과테말라 (Guatemala)" },
    { code: "GU", label: "괌 (Guam)" },
    { code: "GD", label: "그레나다 (Grenada)" },
    { code: "GR", label: "그리스 (Greece)" },
    { code: "GN", label: "기니 (Guinea)" },
    { code: "GW", label: "기니비사우 (Guinea-Bissau)" },
    { code: "NA", label: "나미비아 (Namibia)" },
    { code: "NR", label: "나우루 (Nauru)" },
    { code: "NG", label: "나이지리아 (Nigeria)" },
    { code: "SS", label: "남수단 (South Sudan)" },
    { code: "ZA", label: "남아프리카 공화국 (South Africa)" },
    { code: "NL", label: "네덜란드 (Netherlands)" },
    { code: "NP", label: "네팔 (Nepal)" },
    { code: "NO", label: "노르웨이 (Norway)" },
    { code: "NZ", label: "뉴질랜드 (New Zealand)" }
];
